"""
momentum_tight — generated by the Marle-G Strategy Script Builder on 2026-06-11 03:45 IST.

Base: momentum with your mods. PAPER / RESEARCH ONLY — never places real orders.
Backtest at generation time (net of costs, decade store):
  CAGR 2.7% · Sharpe 0.37 · PSR 0.867 · maxDD -10.5% · 181 trades · win 45.3%

  python momentum_tight.py --backtest      # re-run the honest backtest on current data
  python momentum_tight.py --today         # today's qualifying candidates + position sizes
"""
import sys, json, os
sys.path.insert(0, r"C:\Users\siddh\Desktop\spring 2026\580\BNPL\indian-stock-market-tracker")
import marleg_script_builder as B

SPEC = {'above_sma': [50, 200],
 'base': 'momentum',
 'horizon_td': 63,
 'k_atr': 2.5,
 'mom_lookback': 126,
 'name': 'momentum_tight',
 'notional_cap_pct': 15,
 'rank_by': 'momentum',
 'rebalance_days': 10,
 'risk_pct': 1.0,
 'rsi_max': None,
 'take_profit_pct': None,
 'top_n': 4,
 'ud_min': None}


def today():
    spec, _ = B.validate(SPEC)
    C, V = B._panel()
    s = B._signals(C, V, spec)
    i = len(C.index) - 1
    px, atr = s["px"], s["atr"]
    import numpy as np
    rows = []
    for js, sym in enumerate(s["cols"]):
        if not (np.isfinite(px[i, js]) and np.isfinite(atr[i, js]) and atr[i, js] > 0):
            continue
        if 50 in spec["above_sma"] and not px[i, js] > s["s50"][i, js]:
            continue
        if 200 in spec["above_sma"] and not px[i, js] > s["s200"][i, js]:
            continue
        if spec.get("ud_min") is not None and not (np.isfinite(s["ud"][i, js]) and s["ud"][i, js] > spec["ud_min"]):
            continue
        if spec.get("rsi_max") is not None and not (np.isfinite(s["rsi"][i, js]) and s["rsi"][i, js] < spec["rsi_max"]):
            continue
        sc = (s["mom"][i, js] if spec["rank_by"] == "momentum"
              else s["ud"][i, js] if spec["rank_by"] == "ud" else -s["rsi"][i, js])
        if np.isfinite(sc):
            rows.append((float(sc), sym, float(px[i, js]), float(atr[i, js])))
    rows.sort(reverse=True)
    print(f"momentum_tight — candidates for next session (top {spec['top_n']}), {C.index[-1].date()}")
    for sc, sym, p, a in rows[: spec["top_n"]]:
        stop = round(p - spec["k_atr"] * a, 1)
        qty = int((B.CAP * spec["risk_pct"] / 100) // (spec["k_atr"] * a))
        print(f"  {sym:<12} px {p:>9.1f}  stop {stop:>9.1f}  qty {qty:>5}  score {sc:+.2f}")
    if not rows:
        print("  nothing qualifies today")


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    if "--today" in sys.argv:
        today()
    else:
        r = B.simulate(SPEC)
        print(json.dumps(r["stats"], indent=1))
        print("yearly:", r["yearly_ret_pct"])
