"""
Phase B.2 tests --- CAR event-study module.

Exercises `backtest/car_event_study.py` on deterministic synthetic returns
so that:
    * `market_model` recovers injected alpha and betas within tolerance.
    * `abnormal_returns` is a clean residual on the estimation window.
    * `car` sums the AR vector.
    * `aar_across_events` and `bootstrap_car_null` behave predictably under
      a known-zero-mean null.

Warehouse never touched. All fixtures are in-memory.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from backtest.car_event_study import (
    EVENT_WINDOW,
    ESTIMATION_WINDOW,
    EventCAR,
    abnormal_returns,
    aar_across_events,
    bootstrap_car_null,
    car,
    market_model,
    run_single_event,
)
from backtest.event_study import EventWindow


# --------------------------------------------------------------------------
# Synthetic returns panel
# --------------------------------------------------------------------------
def _synthetic_returns(
    n: int = 800,
    alpha_true: float = 0.0005,
    beta_hyg: float = 1.2,
    beta_move: float = -0.01,
    sigma_e: float = 0.015,
    rng_seed: int = 7,
) -> pd.DataFrame:
    """Deterministic returns panel where r_AFRM is generated by a known
    two-factor DGP so we can recover (alpha, betas) via OLS."""
    rng = np.random.default_rng(rng_seed)
    idx = pd.bdate_range("2020-01-01", periods=n)
    r_hyg = 0.0001 + 0.008 * rng.standard_normal(n)
    r_move = 1.5 * rng.standard_normal(n)  # bp-scale diffs around 0
    eps = sigma_e * rng.standard_normal(n)
    r_afrm = alpha_true + beta_hyg * r_hyg + beta_move * r_move + eps
    return pd.DataFrame(
        {"r_AFRM": r_afrm, "r_HYG": r_hyg, "r_MOVE": r_move},
        index=idx,
    )


# --------------------------------------------------------------------------
# market_model recovers known coefficients
# --------------------------------------------------------------------------
def test_market_model_recovers_alpha_and_betas():
    df = _synthetic_returns(alpha_true=0.001, beta_hyg=1.5, beta_move=-0.02,
                            sigma_e=0.008, n=1200)
    fit = market_model(
        df, ticker="AFRM", factors=("HYG", "MOVE"),
        start=df.index[0], end=df.index[-1],
    )
    assert abs(fit.alpha - 0.001) < 5e-4
    assert abs(fit.beta[0] - 1.5) < 0.05
    assert abs(fit.beta[1] - (-0.02)) < 0.01
    assert 0.005 < fit.sigma_e < 0.015


def test_market_model_sigma_e_matches_noise_scale():
    df = _synthetic_returns(sigma_e=0.02, n=1500)
    fit = market_model(
        df, ticker="AFRM", factors=("HYG", "MOVE"),
        start=df.index[0], end=df.index[-1],
    )
    # Residual std must be within 10% of injected sigma.
    assert 0.018 < fit.sigma_e < 0.022


# --------------------------------------------------------------------------
# abnormal_returns + car
# --------------------------------------------------------------------------
def test_abnormal_returns_mean_is_near_zero_on_estimation_window():
    df = _synthetic_returns(n=1000)
    fit = market_model(df, "AFRM", ("HYG", "MOVE"),
                       df.index[0], df.index[-1])
    ar = abnormal_returns(df, "AFRM", fit, df.index[0], df.index[-1])
    # AR on the fitting window should have (very close to) zero mean --- OLS
    # residuals are orthogonal to the regressors by construction.
    assert abs(float(ar.mean())) < 1e-12


def test_car_sums_ar_vector():
    s = pd.Series([0.01, -0.005, 0.003, 0.0, -0.002])
    assert abs(car(s) - 0.006) < 1e-12


# --------------------------------------------------------------------------
# run_single_event shape
# --------------------------------------------------------------------------
def test_run_single_event_returns_correct_length_ar():
    df = _synthetic_returns(n=1200)
    catalyst_idx = 800
    w = EventWindow(name="SYN", catalyst_date=df.index[catalyst_idx].date())
    ev = run_single_event(df, "AFRM", ("HYG", "MOVE"), w)
    expected = EVENT_WINDOW[1] - EVENT_WINDOW[0] + 1
    assert ev.n_event_days == expected
    assert len(ev.ar) == expected
    assert ev.sigma_e > 0


# --------------------------------------------------------------------------
# aar_across_events
# --------------------------------------------------------------------------
def test_aar_averages_across_events():
    df = _synthetic_returns(n=1200)
    events = []
    for i in (600, 700, 800, 900):
        w = EventWindow(name=f"SYN_{i}", catalyst_date=df.index[i].date())
        events.append(run_single_event(df, "AFRM", ("HYG", "MOVE"), w))
    aar = aar_across_events(events)
    expected = EVENT_WINDOW[1] - EVENT_WINDOW[0] + 1
    assert len(aar) == expected
    # Since the underlying DGP has no true event effect, the AAR should be
    # small in magnitude (within ~3 residual-sigma of zero at any offset).
    assert abs(float(aar.mean())) < 0.01


# --------------------------------------------------------------------------
# bootstrap_car_null
# --------------------------------------------------------------------------
def test_bootstrap_preserves_null_under_random_catalysts():
    """With no true event effect, the observed mean CAR on randomly-placed
    catalysts and the bootstrap null distribution should agree in distribution.
    In particular, the bootstrap t-stat should not be extreme.
    """
    df = _synthetic_returns(n=1400, alpha_true=0.0, rng_seed=3)
    events = []
    for i in (800, 900, 1000, 1100):
        w = EventWindow(name=f"SYN_{i}", catalyst_date=df.index[i].date())
        events.append(run_single_event(df, "AFRM", ("HYG", "MOVE"), w))
    # Small bootstrap so the test is fast.
    boot = bootstrap_car_null(
        events, df, "AFRM", ("HYG", "MOVE"), n_boot=200, seed=11,
    )
    assert boot["n_boot_eff"] > 0
    # Under the null, |t_boot| should be well within 3 (generous).
    assert abs(boot["t_boot"]) < 3.0, f"t_boot={boot['t_boot']:+.2f}"
    # CI should bracket the observed mean CAR (same null).
    assert boot["ci95_low"] <= boot["observed_mean_car"] <= boot["ci95_high"] \
        or abs(boot["observed_mean_car"] - boot["null_mean"]) < 2 * boot["null_std"]


def test_bootstrap_determinism_under_fixed_seed():
    df = _synthetic_returns(n=1200, rng_seed=1)
    events = [
        run_single_event(
            df, "AFRM", ("HYG", "MOVE"),
            EventWindow(name=f"SYN_{i}", catalyst_date=df.index[i].date()),
        )
        for i in (700, 800, 900)
    ]
    b1 = bootstrap_car_null(events, df, "AFRM", ("HYG", "MOVE"),
                            n_boot=100, seed=123)
    b2 = bootstrap_car_null(events, df, "AFRM", ("HYG", "MOVE"),
                            n_boot=100, seed=123)
    assert abs(b1["t_boot"] - b2["t_boot"]) < 1e-12
    assert abs(b1["null_mean"] - b2["null_mean"]) < 1e-12
